name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Replace with your PHP version
          extensions: mbstring, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      # Install Composer
      - name: Install Composer
        run: composer install --no-progress --no-suggest

      # Configure the project
      - name: Configure project
        run: |
          cp .env.test .env
          php artisan config:cache

      # Run database migrations
      - name: Run migrations
        run: php artisan migrate --force

      # Start PHP server
      - name: Start PHP server
        run: php -S 127.0.0.1:8000 -t public &
        env:
          APP_ENV: testing

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Replace with your Node.js version

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress --save-dev

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run